### ISSUE TITLE
LaTeX support?

### ISSUE THREAD

**Issue by rodorgas** [ryanfox/sphinx-markdown-tables#14]
LaTeX isn't rendered inside a table.

For example, this code:

```
| Column 1 | Column 2       |
| -------- | -------------- |
| Row 1    | $e^{i\pi}+1=0$ |
```

It's rendered by sphinx-markdown-tables as:
<img width="259" alt="latex by sphinx-markdown-tables" src="https://user-images.githubusercontent.com/8618619/45749832-530aff00-bbe3-11e8-8d54-0ecb8c66d2b1.png">

Another parser (Typora) will render as:
<img width="307" alt="latex by typora" src="https://user-images.githubusercontent.com/8618619/45749866-6ddd7380-bbe3-11e8-821e-30a59da60ec7.png">

**Comment by ryanfox** [comment]
If you have LaTeX outside of a table, is it rendered properly?

**Comment by rodorgas** [comment]
Yes, latex outside of tables are rendered correctly.

**Comment by ryanfox** [comment]
You could use [sphinx's mathjax extension.](http://www.sphinx-doc.org/en/master/usage/extensions/math.html#module-sphinx.ext.mathjax) I have confirmed it works both in regular paragraph and table bodies.

Note from [mathjax's documentation,](https://docs.mathjax.org/en/latest/start.html#tex-and-latex-input)
> The default math delimiters are `$$...$$` and `\[...\]` for displayed mathematics, and `\(...\)` for in-line mathematics. Note in particular that the `$...$` in-line delimiters are **not** used by default.
