### ISSUE TITLE
docutils table not supported

### ISSUE THREAD

**Issue by codejamninja** [ryanfox/sphinx-markdown-tables#15]
Why is this generating raw html tables instead of docutils tables?

```html
<raw format="html" xml:space="preserve">
  <table border="1" class="docutils">
    <thead>
      <tr>
        <th>table</th>
        <th>i</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>m</td>
        <td>i</td>
      </tr>
    </tbody>
  </table>
</raw>
```

**Comment by codejamninja** [comment]
Basically, when I try to visit table, it doesn't work . . .

```py
visit_table(self, node):
  print('visiting table')

vist_raw(self, node):
  print('visiting raw')
```

The following is what prints to the console . . .

```sh
visiting raw
```

Notice that visiting table is not printed to the console.

**Comment by codejamninja** [comment]
Ah, I see what you're doing. You're converting the markdown tables to html tables before sending it to the parser. It would still be much better if this actually converted the markdown tables to a docutil tree.

**Comment by ryanfox** [comment]
Pull requests are welcome if you want to look into it.

**Comment by codejamninja** [comment]
I ended up rebuilding recommonmark to support tables natively. It was much easier.

https://github.com/codejamninja/sphinx-markdown-parser

**Comment by ryanfox** [comment]
Sounds good.
