### ISSUE TITLE
The install_requires of the package specifies a concrete dependency for the markdown package

### ISSUE THREAD

**Issue by dwighthubbard** [ryanfox/sphinx-markdown-tables#21]
The package install_requires is requiring a specific pinned version of the markdown package which makes it impossible to install it with other extensions that require a different version of the markdown package.

If this requirement for that specific version isn't required, it should probably be an abstract dependency as defined at https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by ryanfox** [comment]
The version requirement is loosened in v0.0.13, if that still doesn't suit your needs a PR for the specific issue is welcome.
