### ISSUE TITLE
Pypi markdown dependency different than github

### ISSUE THREAD

**Issue by kenjones21** [ryanfox/sphinx-markdown-tables#24]
The 0.0.10 build on Pypi has a dependency of markdown==3.0.1, but the build here on github lists a dependency of 2.6.11. I'm not sure which is correct but I believe the discrepancy should be fixed.

Pypi link: https://pypi.org/project/sphinx-markdown-tables/#files
Github link to setup.py: https://github.com/ryanfox/sphinx-markdown-tables/blob/master/setup.py

**Comment by ryanfox** [comment]
Good catch, thank you. Fixed.
