### ISSUE TITLE
Extra blank lines causes warning errors to display wrong line number

### ISSUE THREAD

**Issue by barbara-sfx** [ryanfox/sphinx-markdown-tables#26]
I reported an issue with line number errors in the sphinx repo, and they determined the issue didn't exist in their testing until they added the sphinx-markdown-tables extension.

The issue summary is: If a file contains multiple blank lines above the location of an error, the warning displays an incorrect line number for where the error is. (It subtracts the number of blank lines when determining what line number contains the error.)

You can see details and an example project here: https://github.com/sphinx-doc/sphinx/issues/7436

**Comment by ryanfox** [comment]
I'm not clear on something here. This is a plugin for markdown. The files you have in the linked issue are restructured text...

**Comment by barbara-sfx** [comment]
Sorry for the slow reply. Our repo uses both RST and MD files. We (well, the folks at the sphinx-doc repo) have discovered that with the sphinx-markdown-tables extension installed, the line number error can be reproduced even in RST files. So if you take my original zip file, install your extension, and then do the build, you should be able to reproduce the error.

**Comment by ryanfox** [comment]
I think I got to the bottom of it - can you give build [v0.0.15-rc.1](https://github.com/ryanfox/sphinx-markdown-tables/releases/tag/v0.0.15-rc.1) a try?

**Comment by barbara-sfx** [comment]
I'll be back in the office next week but will see if a colleague can try that in the meantime.

**Comment by barbara-sfx** [comment]
Hi @ryanfox - I may not be doing this correctly, but I copied over the version and init files from the zip to my build directory. Is that the right thing to do? The version is showing 14, not 15, but in any case, the error is still there.

**Comment by ryanfox** [comment]
You need to install the new version. Are you working in a virtualenv?

**Comment by barbara-sfx** [comment]
@ryanfox I am not in a virtualenv. How do I install the new version? Do I need to pass something to `pip3 install recommonmark`?

**Comment by ryanfox** [comment]
I'd uninstall the current `sphinx-markdown-tables` you have in your environment (probably `pip3 uninstall sphinx-markdown-tables`, then install the tagged version from github. I think `pip3 install git+git://github.com/ryanfox/sphinx-markdown-tables.git@v0.0.15-rc.1` should do the trick.

**Comment by barbara-sfx** [comment]
@ryanfox Yes, that fixed the problem! Please let me know when/how to tell my co-workers to update their installation. (For now I can give them the instructions you gave me above, but at some point they should reinstall from a release version.) Please @ mention me in your reply - my last day here is June 19 so I've got a lot going on and don't want to miss your reply. Thanks!

**Comment by ryanfox** [comment]
Does the pre-release fix the issue for you? If so, I can tag it and create a real release.

**Comment by barbara-sfx** [comment]
Yes it does. Only thing is the install message still references version .14.

**Comment by ryanfox** [comment]
@barbara-sfx v0.0.15 is now available via `pip install sphinx-markdown-tables` or `pip install --upgrade sphinx-markdown-tables` if it is already installed.
