### ISSUE TITLE
Long text in cell possibility to break it in multiple lines?

### ISSUE THREAD

**Issue by Spacelord09** [ryanfox/sphinx-markdown-tables#28]
Hello!
Is it possible to break a cell into multiple lines?
I've tried it with the following in my css file:
```
.wy-table-responsive {
    overflow-wrap: break-word;
}
```

Here is one of the tables that are supposed to have a line-break inside:
https://spacecdn.de/img/2020/06/25/2020-06-25_00-57-35-90bb4de4-8703-4ce9-8fc2-61a228ec5e5c.png

**Comment by Spacelord09** [comment]
@ryanfox ?

**Comment by ryanfox** [comment]
This isn't really specific to this plugin - it's the behavior of html. Google offers several potential solutions for you.

**Comment by Spacelord09** [comment]
I've found a solution.
