### ISSUE TITLE
License: GPL3 only or GPL3 or later?

### ISSUE THREAD

**Issue by wiene** [ryanfox/sphinx-markdown-tables#30]
From the available information it is not clear to me whether `sphinx-markdown-tables` is licensed under "GPL3 only" or under "GPL3 or later". Could you please clarify the license situation or point me to the location where the precise license is specified in case I overlooked something.

For further information, have a look at https://www.gnu.org/licenses/identify-licenses-clearly.en.html.

**Comment by merkys** [comment]
File `LICENSE` contains verbatim text of GPL3, and `setup.py` gives GPL3 as the license of the code. Thus I would say the license is unambiguous, unless I have overseen something.

**Comment by wiene** [comment]
I think the license text is identical for "GPL3 only" or "GPL3 or later". What makes the difference (to my understanding) is the clause which is mentioned in the addendum of the license and which I cannot find in the `sphinx-markdown-tables` code:
```
    <one line to give the program's name and a brief idea of what it does.>
    Copyright (C) <year>  <name of author>

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
```
The above example is for "GPL3 or later". In case of "GPL3 only" the second section would have to be modified to exclude later versions.

At least this is my layman's understanding. Feel free to correct me if I am wrong.

**Comment by merkys** [comment]
This excerpt comes from file `LICENSE` (standard GPL3 license text), section "How to Apply These Terms to Your New Programs". As far as I know, this section merely suggests how to apply "GPL3" or "GPL3 or later" to a project. I would say the following line of `setup.py` unambiguously identifies "GPL3":

> License :: OSI Approved :: GNU General Public License v3 (GPLv3)

Should the project be licensed as "GPL3 or later", the following classifier would be used:

> License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)

For the list of classifiers refer to https://pypi.org/classifiers/.

**Comment by wiene** [comment]
Thanks for the pointer to the `setup.py` file. I agree that this breaks the ambiguity and makes it clear that the license is "GPL3 only". I hope @ryanfox agrees with our conclusion. ;-)
