### ISSUE TITLE
0.0.15 source package on PyPI broken

### ISSUE THREAD

**Issue by nsoranzo** [ryanfox/sphinx-markdown-tables#31]
The source package for 0.0.15 on https://pypi.org/project/sphinx-markdown-tables/0.0.15/#files doesn't seem to be in the right format.

As a result, trying to install sphinx-markdown-tables on Python 2.7 (for which there is no wheel available) fails.

**Comment by ryanfox** [comment]
[Sphinx itself only supports python 3.5+,](https://www.sphinx-doc.org/en/3.x/usage/installation.html#overview) so this package doesn't support python 2.

**Comment by nsoranzo** [comment]
The source package for 0.0.15 is broken any way, independently of the Python version:

```
$ pip3 install --no-binary sphinx-markdown-tables sphinx-markdown-tables==0.0.15
ERROR: Could not find a version that satisfies the requirement sphinx-markdown-tables==0.0.15 (from versions: 0.0.15.linux-x86_64, 0.0.1, 0.0.3, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.12, 0.0.13, 0.0.14)
ERROR: No matching distribution found for sphinx-markdown-tables==0.0.15
```

The same works fine with e.g. version 0.0.14 .

**Comment by ryanfox** [comment]
Curious as to why you want `--no-binary`, there is a wheel.
At any rate, there is a cross-platform source distribution uploaded to pypi for v.15 as well now too.

**Comment by nsoranzo** [comment]
Thank you for the fix!
