### ISSUE TITLE
Markdown 3.4 causes TypeError due to breaking changes

### ISSUE THREAD

**Issue by james-iohk** [ryanfox/sphinx-markdown-tables#36]
Markdown 3.4 has just been released and it brings breaking changes to [v0.0.15](https://github.com/ryanfox/sphinx-markdown-tables/releases/tag/v0.0.15)

```
...lib/python3.7/site-packages/sphinx_markdown_tables/__init__.py", line 24, in process_tables
    table_processor = markdown.extensions.tables.TableProcessor(md.parser)
TypeError: __init__() missing 1 required positional argument: 'config'
```

See [Python-Markdown 3.4 Release Notes](https://github.com/Python-Markdown/markdown/blob/3.4/docs/change_log/release-3.4.md#python-markdown-34-release-notes)

Fix required here: https://github.com/ryanfox/sphinx-markdown-tables/blob/master/sphinx_markdown_tables/__init__.py#L24

**Comment by Dzordzu** [comment]
For now I suggest `pip install  git+https://github.com/Dzordzu/sphinx-markdown-tables.git@markdown-patch`

**Comment by frgfm** [comment]
I can confirm, I experienced the same problem today. Adding `markdown<3.4.0` to the version specifiers for now!

**Comment by tdene** [comment]
Also experiencing the same issue, as is elyra-ai/elyra#2837

**Comment by tsibley** [comment]
If you're now experiencing similar TypeErrors because you worked around this issue by pinning `markdown<3.4` (or equivalent), see https://github.com/ryanfox/sphinx-markdown-tables/issues/38.
