### ISSUE TITLE
Installation with pip directly in Lib/site-packages

### ISSUE THREAD

**Issue by Laefy** [ryanfox/sphinx-markdown-tables#5]
Is it normal that setup.py (and sphinx_markdown_tables.py but there's less risks of collisions) are installed directly in Python36/Lib/site-packages/ instead of in a new folder Python36/Lib/site-packages/sphinx_markdown_tables/ ?
And also, by the way, README.md is not copied added.

**Comment by ryanfox** [comment]
There is no strong argument I know of to structure it one way or the other - [Kenneth Reitz suggests single files can live in the top level:](https://www.kennethreitz.org/essays/repository-structure-and-python)

> If your module consists of only a single file, you can place it directly in the root of your repository:
    `./sample.py`

The README is also included as the package's long description - do you have a reason for wanting the markdown file included in the package?

**Comment by Laefy** [comment]
Actually, seems that installing with pip install git+https://github.com/ryanfox/sphinx-markdown-tables/ causes the issue. Directly install with pip install sphinx-markdown-tables works well. Sorry for my mistake.
