### ISSUE TITLE
Python2.7 PiPy package out of date -- currently 0.0.3

### ISSUE THREAD

**Issue by haebou** [ryanfox/sphinx-markdown-tables#7]
The pip package for py 2.7 is still on 0.0.3, while py 3.7 has the latest version, 0.0.6. This means the newline fixes aren't available for 2.7.

**Comment by ryanfox** [comment]
0.0.6 is now uploaded for python 2.

I can continue to upload python 2 compatible packages, but you shouldn't consider them supported - if compatibility is an issue for you, you should consider moving to python 3.

**Comment by haebou** [comment]
Excellent, thanks Ryan!
