### ISSUE TITLE
sphinx-markdown-tables can't work well for the latest recommonark

### ISSUE THREAD

**Issue by cyjseagull** [ryanfox/sphinx-markdown-tables#8]
hello,

     I'm using the latest recommonmark. And use sphinx-markdown-tables as one extension of it. 
     However, I find that sphinx-markdown-tables works well in the old version recommonmark installed by `pip install recommonmark`, but the tables are non-display when using the latest recommonmark installed by `pip install git+https://github.com/rtfd/recommonmark`.
      Could you please help me with this problem. Thanks a lot！

**Comment by ryanfox** [comment]
Do you get any error messages?

**Comment by cyjseagull** [comment]
There are no any error messages.

**Comment by cyjseagull** [comment]
There are no any error messages. I think you can have a try~

**Comment by ryanfox** [comment]
If it works with the latest stable release of recommonmark, I don't know that there is anything to be done. If there is a reason to support the development version, I'm willing to listen, but in general you shouldn't count on unstable releases working out of the box.

**Comment by vincent221174** [comment]
Hello,
I encounter the same issue.
The reason why I switched recently on the git 'development version' of recommonmark was that the .md link to another .md was broken during html generation and build fail. My version alignment is commonmark-0.7.5 recommonmark-0.4.0.  Now that this property is satisfied, I reach that issue as a regression.  If any news, I take, otherwise I will give an eye very soon.

**Comment by phyng** [comment]
@vincent221174

I have the same issue, so I create a patch to work with `pip install recommonmark`.

save this code to `patch.py`, and import patch in `conf.py`, after this `sphinx-markdown-tables` and `recommonmark` are all works correct.

You may remove build dir and rebuild all to see the output.

## patch.py

```
# coding: utf-8

from recommonmark.parser import CommonMarkParser, _SectionHandler, append_inlines
from CommonMark import DocParser
from docutils import nodes


def parse(self, inputstring, document):
    self._patch_id = 0
    self.setup_parse(inputstring, document)

    self.document = document
    self.current_node = document
    self.section_handler = _SectionHandler(document)

    parser = DocParser()

    ast = parser.parse(inputstring + '\n')

    self.convert_block(ast)

    self.finish_parse()


# Blocks
def section(self, block):
    self._patch_id += 1
    new_section = nodes.section()
    new_section.line = block.start_line
    new_section['level'] = block.level

    title_node = nodes.title()
    title_node.line = block.start_line
    append_inlines(title_node, block.inline_content)
    new_section.append(title_node)
    name = nodes.fully_normalize_name(title_node.astext())
    new_section['names'].append(name)
    self.current_node.document.note_implicit_target(new_section, new_section)
    # nodes.make_id(name)
    new_section['ids'].append('id' + str(self._patch_id))

    self.section_handler.add_new_section(new_section, block.level)
    self.current_node = new_section


CommonMarkParser.parse = parse
CommonMarkParser.section = section

```

## conf.py

```
import path.to.patch  # noqa

...other config
```
